sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run react-test npm test -- --coverage

after_success:
    - docker build -t mohankumart/multi-client ./client
    - docker build -t mohankumart/multi-nginx ./nginx
    - docker build -t mohankumart/multi-server ./server
    - docker build -t mohankumart/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - docker push mohankumart/multi-client 
    - docker push mohankumart/multi-nginx 
    - docker push mohankumart/multi-server
    - docker push mohankumart/multi-worker

deploy:
    provider: elasticbeanstlak
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstlak-us-west-346tdf
    bucket_path: docker-multi
    on:
        branch: master
    secret_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SCRET_KEY
        secure: true

        





